[workspace]
members = [
    "crates/p5136-client-oracle",
    "crates/p5136-cli",
    "crates/p5136-connector",
    "crates/p5136-core",
    "crates/p5136-profile",
    "crates/p5136-rho5",
    "crates/p5136-server",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AFL-3.0"
rust-version = "1.94"
version = "0.2.4"

[workspace.dependencies]
anyhow = "1.0"
base64 = "0.22"
cap-fs-ext = "4.0.2"
cap-std = "4.0.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
fs2 = "0.4"
flate2 = "1.1"
md-5 = "0.10"
local-ip-address = "0.6.13"
rand = "0.9"
quick-xml = "0.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2.0"
tokio = { version = "1.49", features = [
    "io-util",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
unicode-casefold = "0.2"
unicode-normalization = "0.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
