[package]
name = "p5136-connector"
description = "Cross-platform connector core for KartRider P5136"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
flate2 = "1.1"
fs2 = "0.4"
p5136-core = { path = "../p5136-core" }
sha2.workspace = true
tempfile = "3.23"
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
base64 = "0.22"

[lints]
workspace = true
