[package]
name = "p5136-server"
description = "Tokio server runtime for the KartRider P5136 client"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
p5136-core = { path = "../p5136-core" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
