[package]
name = "p5136-server"
description = "Tokio server runtime for the KartRider P5136 client"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
p5136-core = { path = "../p5136-core" }
p5136-profile = { path = "../p5136-profile" }
rand.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.23"

[lints]
workspace = true
